spring: 
   datasource:
      username: teste
      password: teste
      url: jdbc:h2:mem:testdb
   jpa:
      properties:
         hibernate.show_sql: true
         hibernate.format_sql: true
      hibernate:
         ddl-auto: create-drop
         database-platform: org.hibernate.dialect.H2Dialect